controller_list:
  - name: fake_arm_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
  - name: fake_hand_controller
    joints:
      - lh_WRJ2
      - lh_WRJ1
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
  - name: fake_arm_and_hand_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
      - lh_WRJ2
      - lh_WRJ1
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
  - name: fake_arm_and_wrist_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
      - lh_WRJ2
      - lh_WRJ1
  - name: fake_first_finger_controller
    joints:
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
  - name: fake_middle_finger_controller
    joints:
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
  - name: fake_ring_finger_controller
    joints:
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
  - name: fake_little_finger_controller
    joints:
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
  - name: fake_thumb_controller
    joints:
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
initial:  # Define initial robot poses.
  - group: arm
    pose: ready
  - group: hand
    pose: open