sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /table_top_points
    max_range: 1.0
    point_subsample: 1
    padding_offset: 0.001
    padding_scale: 1
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud_table_top

